# Generated by Django 5.1.7 on 2025-03-29 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_groceryitem_bought_at_groceryitem_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groceryitem",
            name="bought_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bought_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
